site_name: Vitte RFCs
site_description: Propositions de conception du langage Vitte
site_url: https://vitte-lang.github.io/vitte/
repo_url: https://github.com/vitte-lang/vitte
repo_name: vitte-lang/vitte

# La doc vit dans rfcs/
docs_dir: rfcs
site_dir: site

theme:
  name: material
  language: fr
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji

nav:
  - Accueil: index.md
  - Template: 0000-template.md
  - RFCs:
      - "0001 — Core Syntax and Keywords": 0001-core-syntax-and-keywords.md
      - "0002 — Module System": 0002-module-system.md
      - "0003 — Memory Model and Ownership": 0003-memory-model-and-ownership.md
      - "0004 — Error Handling": 0004-error-handling.md
      - "0005 — FFI and Interoperability": 0005-ffi-and-interoperability.md
      - "0006 — Async/Await & Concurrency": 0006-async-await-concurrency.md
      - "0007 — Pattern Matching": 0007-pattern-matching.md
      - "0008 — Macro System": 0008-macro-system.md
      - "0009 — Standard Library Structure": 0009-std-library-structure.md
      - "0010 — Package Manager (vitpm)": 0010-package-manager-vitpm.md
      - "0011 — Compiler Architecture": 0011-compiler-architecture.md
      - "0012 — Bytecode and VM": 0012-bytecode-and-vm.md
      - "0013 — Security Threat Model": 0013-security-threat-model.md
      - "0014 — Tooling Integration": 0014-tooling-integration.md
      - "0015 — IDE and LSP Support": 0015-ide-and-lsp-support.md
      - "0016 — Build System and CI": 0016-build-system-and-ci.md
      - "0017 — Testing and Benchmarking": 0017-testing-and-benchmarking.md
      - "0018 — Formatting Style and Lints": 0018-formatting-style-and-lints.md
      - "0019 — Distribution and Installation": 0019-distribution-and-installation.md
      - "0020 — Governance and Evolution": 0020-governance-and-evolution.md
      - "0020 — Internationalization and Localization": 0020-internationalization-and-localization.md
      - "0021 — Garbage Collection vs Manual Memory": 0021-garbage-collection-vs-manual-memory.md
      - "0021 — Internationalization / Localization": 0021-internationalization-localization.md
      - "0022 — Embedded Systems Programming": 0022-embedded-systems-programming.md
      - "0022 — Reflection and Metaprogramming": 0022-reflection-and-metaprogramming.md
      - "0023 — Serialization and Deserialization": 0023-serialization-and-deserialization.md
      - "0023 — WebAssembly & Web Integration": 0023-webassembly-web-integration.md
      - "0024 — AI/ML & Data Science": 0024-ai-ml-data-science.md
      - "0024 — Networking and I/O": 0024-networking-and-io.md
      - "0025 — Networking & Distributed Systems": 0025-networking-distributed-systems.md
      - "0025 — Parallelism & SIMD": 0025-parallelism-and-simd.md
      - "0026 — Mobile & Cross‑Platform": 0026-mobile-cross-platform.md
      - "0026 — WebAssembly & Embedded Support": 0026-webassembly-and-embedded-support.md
      - "0027 — Game Development & Graphics": 0027-game-development-graphics.md
      - "0027 — Versioning & SemVer Policy": 0027-versioning-and-semver-policy.md
      - "0028 — Blockchain & Smart Contracts": 0028-blockchain-smart-contracts.md
      - "0028 — Governance & RFC Process": 0028-governance-and-rfc-process.md
      - "0029 — Operating System Development": 0029-operating-system-development.md
      - "0029 — Standard Error Codes & Diagnostics": 0029-standard-error-codes-and-diagnostics.md
      - "0030 — Debugging & Profiling Tools": 0030-debugging-and-profiling-tools.md
      - "0030 — Quantum Computing — Future": 0030-quantum-computing-future.md
      - "0031 — Energy Efficiency & Green Computing": 0031-energy-efficiency-green-computing.md
      - "0032 — AI/ML Integration": 0032-ai-ml-integration.md
      - "0033 — Augmented & Virtual Reality": 0033-augmented-reality-virtual-reality.md
      - "0034 — Space Computing & Aerospace": 0034-space-computing-aerospace.md
      - "0035 — Blockchain, Aerospace & Defense": 0035-blockchain-aerospace-defense.md
      - "0036 — Cybersecurity Framework": 0036-cybersecurity-framework.md
      - "0037 — Edge Computing & IoT Security": 0037-edge-computing-iot-security.md
      - "0038 — Neural Interfaces / BCI": 0038-neural-interfaces-bci.md
      - "0039 — Genomics & Bioinformatics": 0039-genomics-bioinformatics.md
      - "0040 — Quantum Communication": 0040-quantum-communication.md
      - "0041 — Green Computing": 0041-green-computing.md
      - "0042 — Ethical AI": 0042-ethical-ai.md
      - "0043 — Robotics & Autonomous Systems": 0043-robotics-autonomous.md
      - "0044 — Smart Cities": 0044-smart-cities.md
      - "0045 — Space Colonization": 0045-space-colonization.md
      - "0046 — Metaverse / VR": 0046-metaverse-vr.md
      - "0047 — Blockchain dApps": 0047-blockchain-dapps.md
      - "0048 — Neuromorphic Computing": 0048-neuromorphic.md
      - "0049 — Digital Democracy": 0049-digital-democracy.md
      - "0050 — Posthuman Computing": 0050-posthuman-computing.md
      - "0051 — Exascale Computing": 0051-exascale-computing.md
      - "0052 — Synthetic Biology": 0052-synthetic-biology.md
      - "0053 — Interstellar Networks": 0053-interstellar-networks.md
