# rustfmt.toml — Vitte workspace (Rust 1.82)

# ===== Largeurs & heuristiques =====
max_width = 100
comment_width = 100
use_small_heuristics = "Max"   # garde les blocs lisibles, évite l’éclatement gratuit
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# ===== Imports =====
reorder_imports = true
imports_granularity = "Module"     # regroupe par module (std::..., crate::..., etc.)
group_imports = "StdExternalCrate" # groupes: std | extern | crate
reorder_modules = true

# ===== Docs & commentaires =====
wrap_comments = true
normalize_comments = true
format_code_in_doc_comments = true
format_strings = true
normalize_doc_attributes = true

# ===== Virgules / découpages =====
trailing_comma = "Vertical"        # ajoute des virgules sur les listes multilignes
match_block_trailing_comma = true
binop_separator = "Front"          # l’opérateur passe en début de ligne lors d’un wrap

# ===== Mise en forme des constructs =====
merge_derives = true
match_arm_blocks = true
match_arm_leading_pipes = "Preserve"

# Seuils de bascule (aide rustfmt pour décider quand éclater sur plusieurs lignes)
array_width = 80
attr_fn_like_width = 70
chain_width = 80
fn_call_width = 80
struct_lit_width = 80

# ===== Alignements légers (pragmatiques) =====
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20

# ===== Divers sûrs =====
edition = "2021"                   # redondant avec Cargo, mais explicite ici
hex_literal_case = "Lower"

# ===== Expériences à éviter (gardons stable) =====
# version = "Two"   # ⚠️ Ne pas activer: style rustfmt v2 non finalisé sur stable
