[package]
name        = "vitte-opt"
description = "Passes & analyses pour l'IR Vitte : dominators, liveness, framework de passes."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = { workspace = true }

keywords   = ["vitte", "optimizer", "compiler", "ir"]
categories = ["compilers", "data-structures", "no-std"]

[lib]
path = "src/lib.rs"

[features]
# Par défaut on s'appuie sur la std (reste no_std via `alloc`)
default = ["std"]
std     = []

# Export optionnel des structures via Serde
serde   = ["dep:serde"]

[dependencies]
serde = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                       = "warn"
pedantic                  = "warn"
nursery                   = "warn"
module_name_repetitions   = "allow"
too_many_lines            = "allow"
doc_markdown              = "allow"
