[package]
name        = "vitte-cs2d"
description = "Utilitaires 2D compacts et solides pour Vitte : vecteurs, matrices, géométrie, collisions, spatial hash, pathfinding A*, RNG."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = { workspace = true }

keywords   = ["vitte", "2d", "math", "geometry", "pathfinding", "game"]
categories = ["game-development", "mathematics", "data-structures"]

[lib]
name       = "vitte_cs2d"
path       = "src/lib.rs"
crate-type = ["rlib"]

[features]
# Par défaut on s'appuie sur la std (HashMap/HashSet, etc.)
default = ["std"]

# Drapeau std homogène avec le reste du workspace
std = []

# Utiliser f64 au lieu de f32
f64 = []

# Sérialisation (types math/geom, options) via serde
serde = ["dep:serde"]

[dependencies]
# Hérite du workspace (déjà déclaré dans [workspace.dependencies])
serde = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json        = { workspace = true }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                     = "warn"
pedantic                = "warn"
nursery                 = "warn"
module_name_repetitions = "allow"
too_many_lines          = "allow"
doc_markdown            = "allow"

[package.metadata.docs.rs]
all-features        = false
features            = ["std", "serde"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]
